import "./style.css";

export type Locale = "en" | "pl";

export const text = {
  en: {
    eyebrow: "Creator intelligence / cached demo",
    title: "Find the peak.",
    subtitle: "We are building an intelligence engine that identifies what matters most and what can translate into stronger video viewership for any YouTube channel. In the meantime, explore this demo based on MrBeast’s public channel data.",
    demo: "DEMO PROFILE",
    explore: "Explore the full demo",
    videos: "videos",
    subscribers: "subscribers",
    analyzed: "analyzed",
    top: "Top performers",
    bottom: "Needs attention",
    recent: "Recent signal",
    pattern: "What stands out",
    distribution: "Performance distribution",
    distributionHelp: "Every dot is a video. Violet marks the strongest tail, green the selected sample, and gray the rest of the observed catalog.",
    featureDiff: "What separates Top from Worst",
    featureDiffHelp: "Exploratory differences between the top and bottom performance groups. These are associations, not causal claims.",
    topGroup: "Top",
    worstGroup: "Worst",
    pairDiff: "Strong feature combinations",
    pairDiffHelp: "Only combinations with a strong observed difference are shown. This is exploratory association, not causality.",
    shap: "Explainable AI (SHAP)",
    shapHelp: "SHAP shows which observable features move a model prediction up or down. It describes the model, not causality.",
    globalShap: "Global SHAP pattern",
    shapBase: "Base",
    shapPrediction: "Prediction",
    previous: "Previous",
    next: "Next",
    shapSliderLabel: "Browse SHAP videos",
    causal: "Causal exploration",
    causalHelp: "Observational comparisons are shown only when sample size and overlap support a responsible interpretation.",
    causalGuide: "How to read the plots: each dot is one video; the boxplot shows the middle 50% of outcomes, with the line inside marking the median. The y-axis is the log age-normalized view rate — a view-performance measure adjusted for how long a video has been published, then log-scaled so extreme hits do not dominate the chart. The 95% interval is the uncertainty range around the estimated effect; a wide interval means less precision, and an interval crossing zero means the direction is not conclusive.",
    watch: "Watch on YouTube",
    views: "views",
    likes: "likes",
    print: "Print report",
    language: "PL / EN",
    baseline: "chronological baseline",
    selected: "Selected for analysis",
    noCausal: "No treatment met the sample and overlap conditions. No unreliable causal claim is shown.",
    modelUnavailable: "The cached demo has no reliable SHAP model for this snapshot.",
    quickLinks: "Quick links",
    joinShort: "Join waiting list",
    howToTitle: "How to use this demo",
    howToText: "Start with the Executive summary, compare Top performers with Needs attention, then use Explain and Causal exploration for deeper analysis.",
    interactionHint: "Hover a point for details. Click a point to open the video preview.",
    mobileInteractionHint: "Tap a point to inspect the video.",
    pointDetail: "Click a point to inspect that video.",
    showAll: "Show all",
    hideAll: "Hide all",
    treated: "Treated",
    control: "Control",
    treatmentDefinition: "Treatment definition",
    observedDifference: "observed difference",
    executiveSummary: "Executive summary",
    reportLink: "Overview",
    distributionLink: "Distribution",
    shapLink: "SHAP",
    causalLink: "Causal",
    comingSoonTitle: "More creator intelligence is coming soon.",
    comingSoonText: "SNAPIK is preparing additional creator reports and tools. Share your e-mail address to subscribe to the waiting list!",
    waitingListSoon: "Subscribe to join the waiting list",
    waitlistEmail: "Your email address",
    waitlistButton: "Join the waiting list",
    waitlistSuccess: "Thanks — you are on the waiting list.",
    waitlistError: "Something went wrong. Please try again.",
    pauseVideo: "Pause video",
    resumeVideo: "Resume video",
  },
  pl: {
    eyebrow: "Inteligencja twórców / demo z cache",
    title: "Znajdź szczyt.",
    subtitle: "Pracujemy nad silnikiem, który wychwytuje najważniejsze czynniki i pokazuje, co może przekładać się na lepszą oglądalność filmów dowolnego kanału YouTube. W międzyczasie zapraszamy do obejrzenia dema opartego na publicznych danych kanału MrBeast.",
    demo: "PROFIL DEMO",
    explore: "Otwórz pełne demo",
    videos: "filmów",
    subscribers: "subskrybentów",
    analyzed: "przeanalizowano",
    top: "Najlepsze filmy",
    bottom: "Wymaga uwagi",
    recent: "Ostatni sygnał",
    pattern: "Najważniejsze wzorce",
    distribution: "Rozkład wyników",
    distributionHelp: "Każda kropka to film. Fiolet oznacza najmocniejszy ogon, zieleń wybraną próbę, a szarość resztę katalogu.",
    featureDiff: "Cechy różniące Top od Worst",
    featureDiffHelp: "Eksploracyjne różnice między grupami najlepszych i najsłabszych filmów. To zależności, a nie twierdzenia przyczynowe.",
    topGroup: "Top",
    worstGroup: "Worst",
    pairDiff: "Silne kombinacje cech",
    pairDiffHelp: "Pokazujemy tylko kombinacje z wyraźną zaobserwowaną różnicą. To zależność eksploracyjna, a nie przyczynowość.",
    shap: "Wyjaśnialne AI (SHAP)",
    shapHelp: "SHAP pokazuje, które obserwowalne cechy podnoszą lub obniżają predykcję modelu. Nie opisuje przyczynowości.",
    globalShap: "Globalny wzorzec SHAP",
    shapBase: "Baza",
    shapPrediction: "Predykcja",
    previous: "Poprzedni",
    next: "Następny",
    shapSliderLabel: "Przeglądaj filmy SHAP",
    causal: "Analiza przyczynowa",
    causalHelp: "Porównania obserwacyjne pokazujemy tylko wtedy, gdy liczebność i nakładanie grup pozwalają na odpowiedzialną interpretację.",
    causalGuide: "Jak czytać wykresy: każda kropka to jeden film; boxplot pokazuje środkowe 50% wyników, a linia w środku oznacza medianę. Oś Y przedstawia logarytmiczny, znormalizowany względem wieku filmu wskaźnik wyświetleń — wynik uwzględnia, jak długo film jest opublikowany, a logarytm ogranicza wpływ skrajnych viralowych wyników. Przedział 95% pokazuje niepewność oszacowanego efektu; szeroki przedział oznacza mniejszą precyzję, a przedział obejmujący zero oznacza, że kierunek efektu nie jest rozstrzygający.",
    watch: "Otwórz na YouTube",
    views: "wyświetleń",
    likes: "polubień",
    print: "Drukuj raport",
    language: "EN / PL",
    baseline: "chronologiczny model bazowy",
    selected: "Wybrane do analizy",
    noCausal: "Żaden wariant nie spełnił warunków liczebności i nakładania grup. Nie pokazujemy niewiarygodnego wniosku przyczynowego.",
    modelUnavailable: "W tym zrzucie demo nie ma wiarygodnego modelu SHAP.",
    quickLinks: "Szybkie przejście",
    joinShort: "Lista oczekujących",
    howToTitle: "Jak korzystać z tego demo",
    howToText: "Zacznij od podsumowania, porównaj najlepsze i najsłabsze filmy, a następnie przejdź do sekcji Explain i Causal, aby zobaczyć głębszą analizę.",
    interactionHint: "Najedź na punkt, aby zobaczyć szczegóły. Kliknij punkt, aby otworzyć podgląd filmu.",
    mobileInteractionHint: "Dotknij punktu, aby zobaczyć film.",
    pointDetail: "Kliknij punkt, aby zobaczyć podgląd filmu.",
    showAll: "Pokaż wszystkie",
    hideAll: "Ukryj wszystkie",
    treated: "Treatment",
    control: "Kontrola",
    treatmentDefinition: "Definicja treatmentu",
    observedDifference: "zaobserwowana różnica",
    executiveSummary: "Podsumowanie",
    reportLink: "Przegląd",
    distributionLink: "Rozkład",
    shapLink: "SHAP",
    causalLink: "Przyczynowość",
    comingSoonTitle: "Więcej analiz twórców już wkrótce.",
    comingSoonText: "SNAPIK przygotowuje dodatkowe raporty i narzędzia dla twórców. Podaj swój adres e-mail, aby zapisać się na listę oczekujących!",
    waitingListSoon: "Zapisz się na listę oczekujących",
    waitlistEmail: "Twój adres e-mail",
    waitlistButton: "Dołącz do listy oczekujących",
    waitlistSuccess: "Dziękujemy — jesteś na liście oczekujących.",
    waitlistError: "Coś poszło nie tak. Spróbuj ponownie.",
    pauseVideo: "Wstrzymaj film",
    resumeVideo: "Wznów film",
  },
} as const;

let currentLocale: Locale = navigator.language.toLowerCase().startsWith("pl") ? "pl" : "en";

export const getCurrentLocale = (): Locale => currentLocale;
export const toggleLocale = (): Locale => { currentLocale = currentLocale === "pl" ? "en" : "pl"; return currentLocale; };

export async function loadDemo(): Promise<any> {
  const response = await fetch(currentLocale === "pl" ? "./data/demo-pl.json" : "./data/demo-en.json");
  if (!response.ok) throw new Error("Could not load the cached demo.");
  return response.json();
}
